// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `playerinfo.jce'
// **********************************************************************

package net.digitcube.hadoop.jce;

import net.digitcube.protocol.JceDisplayer;
import net.digitcube.protocol.JceInputStream;
import net.digitcube.protocol.JceOutputStream;
import net.digitcube.protocol.JceStruct;
import net.digitcube.protocol.JceUtil;

public final class PlayerInfoForHbase extends JceStruct implements
		java.lang.Cloneable {
	public String className() {
		return "PlayerInfo.PlayerInfoForHbase";
	}

	public String fullClassName() {
		return "PlayerInfoForHbase";
	}

	public int actTime = 0;

	public int regTime = 0;

	public int firstLoginDate = 0;

	public int lastLoginDate = 0;

	public int totalOnlineDay = 0;

	public int totalLoginTimes = 0;

	public int totalOnlineTime = 0;

	public int firstPayDate = 0;

	public int lastPayDate = 0;

	public int totalCurrencyAmount = 0;

	public int totalPayTimes = 0;

	public int level = 0;

	public String channel = "";

	public String gameRegion = "";

	public int lastPayOnlineTime = 0;

	public java.util.ArrayList<Integer> onlineDay = null;

	public java.util.ArrayList<PayInfo> payInfoList = null;

	public java.util.ArrayList<OnlineDay> onlineDayList = null;

	public int getActTime() {
		return actTime;
	}

	public void setActTime(int actTime) {
		this.actTime = actTime;
	}

	public int getRegTime() {
		return regTime;
	}

	public void setRegTime(int regTime) {
		this.regTime = regTime;
	}

	public int getFirstLoginDate() {
		return firstLoginDate;
	}

	public void setFirstLoginDate(int firstLoginDate) {
		this.firstLoginDate = firstLoginDate;
	}

	public int getLastLoginDate() {
		return lastLoginDate;
	}

	public void setLastLoginDate(int lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public int getTotalOnlineDay() {
		return totalOnlineDay;
	}

	public void setTotalOnlineDay(int totalOnlineDay) {
		this.totalOnlineDay = totalOnlineDay;
	}

	public int getTotalLoginTimes() {
		return totalLoginTimes;
	}

	public void setTotalLoginTimes(int totalLoginTimes) {
		this.totalLoginTimes = totalLoginTimes;
	}

	public int getTotalOnlineTime() {
		return totalOnlineTime;
	}

	public void setTotalOnlineTime(int totalOnlineTime) {
		this.totalOnlineTime = totalOnlineTime;
	}

	public int getFirstPayDate() {
		return firstPayDate;
	}

	public void setFirstPayDate(int firstPayDate) {
		this.firstPayDate = firstPayDate;
	}

	public int getLastPayDate() {
		return lastPayDate;
	}

	public void setLastPayDate(int lastPayDate) {
		this.lastPayDate = lastPayDate;
	}

	public int getTotalCurrencyAmount() {
		return totalCurrencyAmount;
	}

	public void setTotalCurrencyAmount(int totalCurrencyAmount) {
		this.totalCurrencyAmount = totalCurrencyAmount;
	}

	public int getTotalPayTimes() {
		return totalPayTimes;
	}

	public void setTotalPayTimes(int totalPayTimes) {
		this.totalPayTimes = totalPayTimes;
	}

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getGameRegion() {
		return gameRegion;
	}

	public void setGameRegion(String gameRegion) {
		this.gameRegion = gameRegion;
	}

	public int getLastPayOnlineTime() {
		return lastPayOnlineTime;
	}

	public void setLastPayOnlineTime(int lastPayOnlineTime) {
		this.lastPayOnlineTime = lastPayOnlineTime;
	}

	public java.util.ArrayList<Integer> getOnlineDay() {
		return onlineDay;
	}

	public void setOnlineDay(java.util.ArrayList<Integer> onlineDay) {
		this.onlineDay = onlineDay;
	}

	public java.util.ArrayList<PayInfo> getPayInfoList() {
		return payInfoList;
	}

	public void setPayInfoList(java.util.ArrayList<PayInfo> payInfoList) {
		this.payInfoList = payInfoList;
	}

	public java.util.ArrayList<OnlineDay> getOnlineDayList() {
		return onlineDayList;
	}

	public void setOnlineDayList(java.util.ArrayList<OnlineDay> onlineDayList) {
		this.onlineDayList = onlineDayList;
	}

	public PlayerInfoForHbase() {
		setActTime(actTime);
		setRegTime(regTime);
		setFirstLoginDate(firstLoginDate);
		setLastLoginDate(lastLoginDate);
		setTotalOnlineDay(totalOnlineDay);
		setTotalLoginTimes(totalLoginTimes);
		setTotalOnlineTime(totalOnlineTime);
		setFirstPayDate(firstPayDate);
		setLastPayDate(lastPayDate);
		setTotalCurrencyAmount(totalCurrencyAmount);
		setTotalPayTimes(totalPayTimes);
		setLevel(level);
		setChannel(channel);
		setGameRegion(gameRegion);
		setLastPayOnlineTime(lastPayOnlineTime);
		setOnlineDay(onlineDay);
		setPayInfoList(payInfoList);
		setOnlineDayList(onlineDayList);
	}

	public PlayerInfoForHbase(int actTime, int regTime, int firstLoginDate,
			int lastLoginDate, int totalOnlineDay, int totalLoginTimes,
			int totalOnlineTime, int firstPayDate, int lastPayDate,
			int totalCurrencyAmount, int totalPayTimes, int level,
			String channel, String gameRegion, int lastPayOnlineTime,
			java.util.ArrayList<Integer> onlineDay,
			java.util.ArrayList<PayInfo> payInfoList,
			java.util.ArrayList<OnlineDay> onlineDayList) {
		setActTime(actTime);
		setRegTime(regTime);
		setFirstLoginDate(firstLoginDate);
		setLastLoginDate(lastLoginDate);
		setTotalOnlineDay(totalOnlineDay);
		setTotalLoginTimes(totalLoginTimes);
		setTotalOnlineTime(totalOnlineTime);
		setFirstPayDate(firstPayDate);
		setLastPayDate(lastPayDate);
		setTotalCurrencyAmount(totalCurrencyAmount);
		setTotalPayTimes(totalPayTimes);
		setLevel(level);
		setChannel(channel);
		setGameRegion(gameRegion);
		setLastPayOnlineTime(lastPayOnlineTime);
		setOnlineDay(onlineDay);
		setPayInfoList(payInfoList);
		setOnlineDayList(onlineDayList);
	}

	public boolean equals(Object o) {
		if (o == null) {
			return false;
		}

		PlayerInfoForHbase t = (PlayerInfoForHbase) o;
		return (JceUtil.equals(actTime, t.actTime)
				&& JceUtil.equals(regTime, t.regTime)
				&& JceUtil.equals(firstLoginDate, t.firstLoginDate)
				&& JceUtil.equals(lastLoginDate, t.lastLoginDate)
				&& JceUtil.equals(totalOnlineDay, t.totalOnlineDay)
				&& JceUtil.equals(totalLoginTimes, t.totalLoginTimes)
				&& JceUtil.equals(totalOnlineTime, t.totalOnlineTime)
				&& JceUtil.equals(firstPayDate, t.firstPayDate)
				&& JceUtil.equals(lastPayDate, t.lastPayDate)
				&& JceUtil.equals(totalCurrencyAmount, t.totalCurrencyAmount)
				&& JceUtil.equals(totalPayTimes, t.totalPayTimes)
				&& JceUtil.equals(level, t.level)
				&& JceUtil.equals(channel, t.channel)
				&& JceUtil.equals(gameRegion, t.gameRegion)
				&& JceUtil.equals(lastPayOnlineTime, t.lastPayOnlineTime)
				&& JceUtil.equals(onlineDay, t.onlineDay)
				&& JceUtil.equals(payInfoList, t.payInfoList) && JceUtil
					.equals(onlineDayList, t.onlineDayList));
	}

	public int hashCode() {
		try {
			throw new Exception("Need define key first!");
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		return 0;
	}

	public java.lang.Object clone() {
		java.lang.Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException ex) {
			assert false; // impossible
		}
		return o;
	}

	public void writeTo(JceOutputStream _os) {
		_os.write(actTime, 0);
		_os.write(regTime, 1);
		_os.write(firstLoginDate, 2);
		_os.write(lastLoginDate, 3);
		_os.write(totalOnlineDay, 4);
		_os.write(totalLoginTimes, 5);
		_os.write(totalOnlineTime, 6);
		_os.write(firstPayDate, 7);
		_os.write(lastPayDate, 8);
		_os.write(totalCurrencyAmount, 9);
		_os.write(totalPayTimes, 10);
		_os.write(level, 11);
		_os.write(channel, 12);
		_os.write(gameRegion, 13);
		_os.write(lastPayOnlineTime, 14);
		if (null != onlineDay) {
			_os.write(onlineDay, 15);
		}
		if (null != payInfoList) {
			_os.write(payInfoList, 16);
		}
		if (null != onlineDayList) {
			_os.write(onlineDayList, 17);
		}
	}

	static java.util.ArrayList<Integer> cache_onlineDay;
	static java.util.ArrayList<PayInfo> cache_payInfoList;
	static java.util.ArrayList<OnlineDay> cache_onlineDayList;

	public void readFrom(JceInputStream _is) {
		setActTime((int) _is.read(actTime, 0, true));

		setRegTime((int) _is.read(regTime, 1, true));

		setFirstLoginDate((int) _is.read(firstLoginDate, 2, true));

		setLastLoginDate((int) _is.read(lastLoginDate, 3, true));

		setTotalOnlineDay((int) _is.read(totalOnlineDay, 4, true));

		setTotalLoginTimes((int) _is.read(totalLoginTimes, 5, true));

		setTotalOnlineTime((int) _is.read(totalOnlineTime, 6, true));

		setFirstPayDate((int) _is.read(firstPayDate, 7, true));

		setLastPayDate((int) _is.read(lastPayDate, 8, true));

		setTotalCurrencyAmount((int) _is.read(totalCurrencyAmount, 9, true));

		setTotalPayTimes((int) _is.read(totalPayTimes, 10, true));

		setLevel((int) _is.read(level, 11, true));

		setChannel(_is.readString(12, true));

		setGameRegion(_is.readString(13, true));

		setLastPayOnlineTime((int) _is.read(lastPayOnlineTime, 14, false));

		if (null == cache_onlineDay) {
			cache_onlineDay = new java.util.ArrayList<Integer>();
			Integer __var_4 = 0;
			((java.util.ArrayList<Integer>) cache_onlineDay).add(__var_4);
		}
		setOnlineDay((java.util.ArrayList<Integer>) _is.read(cache_onlineDay,
				15, false));

		if (null == cache_payInfoList) {
			cache_payInfoList = new java.util.ArrayList<PayInfo>();
			PayInfo __var_5 = new PayInfo();
			((java.util.ArrayList<PayInfo>) cache_payInfoList).add(__var_5);
		}
		setPayInfoList((java.util.ArrayList<PayInfo>) _is.read(
				cache_payInfoList, 16, false));

		if (null == cache_onlineDayList) {
			cache_onlineDayList = new java.util.ArrayList<OnlineDay>();
			OnlineDay __var_6 = new OnlineDay();
			((java.util.ArrayList<OnlineDay>) cache_onlineDayList).add(__var_6);
		}
		setOnlineDayList((java.util.ArrayList<OnlineDay>) _is.read(
				cache_onlineDayList, 17, false));

	}

	public void display(java.lang.StringBuilder _os, int _level) {
		JceDisplayer _ds = new JceDisplayer(_os, _level);
		_ds.display(actTime, "actTime");
		_ds.display(regTime, "regTime");
		_ds.display(firstLoginDate, "firstLoginDate");
		_ds.display(lastLoginDate, "lastLoginDate");
		_ds.display(totalOnlineDay, "totalOnlineDay");
		_ds.display(totalLoginTimes, "totalLoginTimes");
		_ds.display(totalOnlineTime, "totalOnlineTime");
		_ds.display(firstPayDate, "firstPayDate");
		_ds.display(lastPayDate, "lastPayDate");
		_ds.display(totalCurrencyAmount, "totalCurrencyAmount");
		_ds.display(totalPayTimes, "totalPayTimes");
		_ds.display(level, "level");
		_ds.display(channel, "channel");
		_ds.display(gameRegion, "gameRegion");
		_ds.display(lastPayOnlineTime, "lastPayOnlineTime");
		_ds.display(onlineDay, "onlineDay");
		_ds.display(payInfoList, "payInfoList");
		_ds.display(onlineDayList, "onlineDayList");
	}

}
