// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `playerinfo.jce'
// **********************************************************************

package net.digitcube.hadoop.jce;

import net.digitcube.protocol.JceDisplayer;
import net.digitcube.protocol.JceInputStream;
import net.digitcube.protocol.JceOutputStream;
import net.digitcube.protocol.JceStruct;
import net.digitcube.protocol.JceUtil;

public final class PlayerMonthInfo extends JceStruct implements
		java.lang.Cloneable {
	public String className() {
		return "PlayerInfo.PlayerMonthInfo";
	}

	public String fullClassName() {
		return "net.digitcube.hadoop.jce.PlayerInfo.PlayerMonthInfo";
	}

	public int firstLoginMonthDate = 0;

	public int lastLoginMonthDate = 0;

	public int firstPayMonthDate = 0;

	public int lastPayMonthDate = 0;

	public String channel = "";

	public String gameRegion = "";

	public int track = 0;

	public int payTrack = 0;

	public int getFirstLoginMonthDate() {
		return firstLoginMonthDate;
	}

	public void setFirstLoginMonthDate(int firstLoginMonthDate) {
		this.firstLoginMonthDate = firstLoginMonthDate;
	}

	public int getLastLoginMonthDate() {
		return lastLoginMonthDate;
	}

	public void setLastLoginMonthDate(int lastLoginMonthDate) {
		this.lastLoginMonthDate = lastLoginMonthDate;
	}

	public int getFirstPayMonthDate() {
		return firstPayMonthDate;
	}

	public void setFirstPayMonthDate(int firstPayMonthDate) {
		this.firstPayMonthDate = firstPayMonthDate;
	}

	public int getLastPayMonthDate() {
		return lastPayMonthDate;
	}

	public void setLastPayMonthDate(int lastPayMonthDate) {
		this.lastPayMonthDate = lastPayMonthDate;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getGameRegion() {
		return gameRegion;
	}

	public void setGameRegion(String gameRegion) {
		this.gameRegion = gameRegion;
	}

	public int getTrack() {
		return track;
	}

	public void setTrack(int track) {
		this.track = track;
	}

	public int getPayTrack() {
		return payTrack;
	}

	public void setPayTrack(int payTrack) {
		this.payTrack = payTrack;
	}

	public PlayerMonthInfo() {
		setFirstLoginMonthDate(firstLoginMonthDate);
		setLastLoginMonthDate(lastLoginMonthDate);
		setFirstPayMonthDate(firstPayMonthDate);
		setLastPayMonthDate(lastPayMonthDate);
		setChannel(channel);
		setGameRegion(gameRegion);
		setTrack(track);
		setPayTrack(payTrack);
	}

	public PlayerMonthInfo(int firstLoginMonthDate, int lastLoginMonthDate,
			int firstPayMonthDate, int lastPayMonthDate, String channel,
			String gameRegion, int track, int payTrack) {
		setFirstLoginMonthDate(firstLoginMonthDate);
		setLastLoginMonthDate(lastLoginMonthDate);
		setFirstPayMonthDate(firstPayMonthDate);
		setLastPayMonthDate(lastPayMonthDate);
		setChannel(channel);
		setGameRegion(gameRegion);
		setTrack(track);
		setPayTrack(payTrack);
	}

	public boolean equals(Object o) {
		if (o == null) {
			return false;
		}

		PlayerMonthInfo t = (PlayerMonthInfo) o;
		return (JceUtil.equals(firstLoginMonthDate, t.firstLoginMonthDate)
				&& JceUtil.equals(lastLoginMonthDate, t.lastLoginMonthDate)
				&& JceUtil.equals(firstPayMonthDate, t.firstPayMonthDate)
				&& JceUtil.equals(lastPayMonthDate, t.lastPayMonthDate)
				&& JceUtil.equals(channel, t.channel)
				&& JceUtil.equals(gameRegion, t.gameRegion)
				&& JceUtil.equals(track, t.track) && JceUtil.equals(payTrack,
				t.payTrack));
	}

	public int hashCode() {
		try {
			throw new Exception("Need define key first!");
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		return 0;
	}

	public java.lang.Object clone() {
		java.lang.Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException ex) {
			assert false; // impossible
		}
		return o;
	}

	public void writeTo(JceOutputStream _os) {
		_os.write(firstLoginMonthDate, 0);
		_os.write(lastLoginMonthDate, 1);
		_os.write(firstPayMonthDate, 2);
		_os.write(lastPayMonthDate, 3);
		_os.write(channel, 4);
		_os.write(gameRegion, 5);
		_os.write(track, 6);
		_os.write(payTrack, 7);
	}

	public void readFrom(JceInputStream _is) {
		setFirstLoginMonthDate((int) _is.read(firstLoginMonthDate, 0, true));

		setLastLoginMonthDate((int) _is.read(lastLoginMonthDate, 1, true));

		setFirstPayMonthDate((int) _is.read(firstPayMonthDate, 2, true));

		setLastPayMonthDate((int) _is.read(lastPayMonthDate, 3, true));

		setChannel(_is.readString(4, true));

		setGameRegion(_is.readString(5, true));

		setTrack((int) _is.read(track, 6, true));

		setPayTrack((int) _is.read(payTrack, 7, true));

	}

	public void display(java.lang.StringBuilder _os, int _level) {
		JceDisplayer _ds = new JceDisplayer(_os, _level);
		_ds.display(firstLoginMonthDate, "firstLoginMonthDate");
		_ds.display(lastLoginMonthDate, "lastLoginMonthDate");
		_ds.display(firstPayMonthDate, "firstPayMonthDate");
		_ds.display(lastPayMonthDate, "lastPayMonthDate");
		_ds.display(channel, "channel");
		_ds.display(gameRegion, "gameRegion");
		_ds.display(track, "track");
		_ds.display(payTrack, "payTrack");
	}

}
