// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `playerinfo.jce'
// **********************************************************************

package net.digitcube.hadoop.jce;

import net.digitcube.protocol.JceDisplayer;
import net.digitcube.protocol.JceInputStream;
import net.digitcube.protocol.JceOutputStream;
import net.digitcube.protocol.JceStruct;
import net.digitcube.protocol.JceUtil;

public final class PlayerDeviceInfo extends JceStruct implements
		java.lang.Cloneable {
	public String className() {
		return "PlayerInfo.PlayerDeviceInfo";
	}

	public String fullClassName() {
		return "net.digitcube.hadoop.jce.PlayerInfo.PlayerDeviceInfo";
	}

	public String brand = "";

	public String resolution = "";

	public String opersystem = "";

	public String country = "";

	public String province = "";

	public String carrier = "";

	public int netType = 0;

	public int gender = 0;

	public int age = 0;

	public int accountType = 0;

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getResolution() {
		return resolution;
	}

	public void setResolution(String resolution) {
		this.resolution = resolution;
	}

	public String getOpersystem() {
		return opersystem;
	}

	public void setOpersystem(String opersystem) {
		this.opersystem = opersystem;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCarrier() {
		return carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	public int getNetType() {
		return netType;
	}

	public void setNetType(int netType) {
		this.netType = netType;
	}

	public int getGender() {
		return gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getAccountType() {
		return accountType;
	}

	public void setAccountType(int accountType) {
		this.accountType = accountType;
	}

	public PlayerDeviceInfo() {
		setBrand(brand);
		setResolution(resolution);
		setOpersystem(opersystem);
		setCountry(country);
		setProvince(province);
		setCarrier(carrier);
		setNetType(netType);
		setGender(gender);
		setAge(age);
		setAccountType(accountType);
	}

	public PlayerDeviceInfo(String brand, String resolution, String opersystem,
			String country, String province, String carrier, int netType,
			int gender, int age, int accountType) {
		setBrand(brand);
		setResolution(resolution);
		setOpersystem(opersystem);
		setCountry(country);
		setProvince(province);
		setCarrier(carrier);
		setNetType(netType);
		setGender(gender);
		setAge(age);
		setAccountType(accountType);
	}

	public boolean equals(Object o) {
		if (o == null) {
			return false;
		}

		PlayerDeviceInfo t = (PlayerDeviceInfo) o;
		return (JceUtil.equals(brand, t.brand)
				&& JceUtil.equals(resolution, t.resolution)
				&& JceUtil.equals(opersystem, t.opersystem)
				&& JceUtil.equals(country, t.country)
				&& JceUtil.equals(province, t.province)
				&& JceUtil.equals(carrier, t.carrier)
				&& JceUtil.equals(netType, t.netType)
				&& JceUtil.equals(gender, t.gender)
				&& JceUtil.equals(age, t.age) && JceUtil.equals(accountType,
				t.accountType));
	}

	public int hashCode() {
		try {
			throw new Exception("Need define key first!");
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		return 0;
	}

	public java.lang.Object clone() {
		java.lang.Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException ex) {
			assert false; // impossible
		}
		return o;
	}

	public void writeTo(JceOutputStream _os) {
		if (null != brand) {
			_os.write(brand, 0);
		}
		if (null != resolution) {
			_os.write(resolution, 1);
		}
		if (null != opersystem) {
			_os.write(opersystem, 2);
		}
		if (null != country) {
			_os.write(country, 3);
		}
		if (null != province) {
			_os.write(province, 4);
		}
		if (null != carrier) {
			_os.write(carrier, 5);
		}
		_os.write(netType, 6);
		_os.write(gender, 7);
		_os.write(age, 8);
		_os.write(accountType, 9);
	}

	public void readFrom(JceInputStream _is) {
		setBrand(_is.readString(0, false));

		setResolution(_is.readString(1, false));

		setOpersystem(_is.readString(2, false));

		setCountry(_is.readString(3, false));

		setProvince(_is.readString(4, false));

		setCarrier(_is.readString(5, false));

		setNetType((int) _is.read(netType, 6, false));

		setGender((int) _is.read(gender, 7, false));

		setAge((int) _is.read(age, 8, false));

		setAccountType((int) _is.read(accountType, 9, false));

	}

	public void display(java.lang.StringBuilder _os, int _level) {
		JceDisplayer _ds = new JceDisplayer(_os, _level);
		_ds.display(brand, "brand");
		_ds.display(resolution, "resolution");
		_ds.display(opersystem, "opersystem");
		_ds.display(country, "country");
		_ds.display(province, "province");
		_ds.display(carrier, "carrier");
		_ds.display(netType, "netType");
		_ds.display(gender, "gender");
		_ds.display(age, "age");
		_ds.display(accountType, "accountType");
	}

}
