// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `playerinfo.jce'
// **********************************************************************

package net.digitcube.hadoop.jce;

import net.digitcube.protocol.JceDisplayer;
import net.digitcube.protocol.JceInputStream;
import net.digitcube.protocol.JceOutputStream;
import net.digitcube.protocol.JceStruct;

public final class PlayerDayInfo extends JceStruct implements
		java.lang.Cloneable {
	public String className() {
		return "PlayerInfo.PlayerDayInfo";
	}

	public String fullClassName() {
		return "PlayerDayInfo";
	}

	public int actTime = 0;

	public int regTime = 0;

	public int firstLoginDate = 0;

	public int lastLoginDate = 0;

	public int totalOnlineDay = 0;

	public int totalLoginTimes = 0;

	public int totalOnlineTime = 0;

	public byte weekOnlineDay = 0;

	public short weekLoginTimes = 0;

	public int weekOnlineTime = 0;

	public int weekCurrencyAmount = 0;

	public short weekPayTimes = 0;

	public byte monthOnlineDay = 0;

	public short monthLoginTimes = 0;

	public int monthOnlineTime = 0;

	public int monthCurrencyAmount = 0;

	public short monthPayTimes = 0;

	public int firstPayDate = 0;

	public int lastPayDate = 0;

	public int totalCurrencyAmount = 0;

	public int totalPayTimes = 0;

	public int level = 0;

	public String channel = "";

	public String gameRegion = "";

	public int track = 0;

	public int payTrack = 0;

	public int lastPayOnlineTime = 0;

	public java.util.ArrayList<Integer> onlineDay = null;

	public java.util.ArrayList<PayInfo> payInfoList = null;

	public java.util.ArrayList<OnlineDay> onlineDayList = null;

	public int lastLoginTime = 0;

	public String uid = "";
	public String country = "";
	public String province = "";
	public byte gender = 0;
	public short age = 0;
	public String accountType = "";
	public String brand = "";
	public String osVersion = "";
	public String resolution = "";
	public String operators = "";
	public int netType = 0;
	public int lastPayAmount = 0;
	public int lastPayTime = 0;

	public int getActTime() {
		return actTime;
	}

	public void setActTime(int actTime) {
		this.actTime = actTime;
	}

	public int getRegTime() {
		return regTime;
	}

	public void setRegTime(int regTime) {
		this.regTime = regTime;
	}

	public int getFirstLoginDate() {
		return firstLoginDate;
	}

	public void setFirstLoginDate(int firstLoginDate) {
		this.firstLoginDate = firstLoginDate;
	}

	public int getLastLoginDate() {
		return lastLoginDate;
	}

	public void setLastLoginDate(int lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public int getTotalOnlineDay() {
		return totalOnlineDay;
	}

	public void setTotalOnlineDay(int totalOnlineDay) {
		this.totalOnlineDay = totalOnlineDay;
	}

	public int getTotalLoginTimes() {
		return totalLoginTimes;
	}

	public void setTotalLoginTimes(int totalLoginTimes) {
		this.totalLoginTimes = totalLoginTimes;
	}

	public int getTotalOnlineTime() {
		return totalOnlineTime;
	}

	public void setTotalOnlineTime(int totalOnlineTime) {
		this.totalOnlineTime = totalOnlineTime;
	}

	public byte getWeekOnlineDay() {
		return weekOnlineDay;
	}

	public void setWeekOnlineDay(byte weekOnlineDay) {
		this.weekOnlineDay = weekOnlineDay;
	}

	public short getWeekLoginTimes() {
		return weekLoginTimes;
	}

	public void setWeekLoginTimes(short weekLoginTimes) {
		this.weekLoginTimes = weekLoginTimes;
	}

	public int getWeekOnlineTime() {
		return weekOnlineTime;
	}

	public void setWeekOnlineTime(int weekOnlineTime) {
		this.weekOnlineTime = weekOnlineTime;
	}

	public int getWeekCurrencyAmount() {
		return weekCurrencyAmount;
	}

	public void setWeekCurrencyAmount(int weekCurrencyAmount) {
		this.weekCurrencyAmount = weekCurrencyAmount;
	}

	public short getWeekPayTimes() {
		return weekPayTimes;
	}

	public void setWeekPayTimes(short weekPayTimes) {
		this.weekPayTimes = weekPayTimes;
	}

	public byte getMonthOnlineDay() {
		return monthOnlineDay;
	}

	public void setMonthOnlineDay(byte monthOnlineDay) {
		this.monthOnlineDay = monthOnlineDay;
	}

	public short getMonthLoginTimes() {
		return monthLoginTimes;
	}

	public void setMonthLoginTimes(short monthLoginTimes) {
		this.monthLoginTimes = monthLoginTimes;
	}

	public int getMonthOnlineTime() {
		return monthOnlineTime;
	}

	public void setMonthOnlineTime(int monthOnlineTime) {
		this.monthOnlineTime = monthOnlineTime;
	}

	public int getMonthCurrencyAmount() {
		return monthCurrencyAmount;
	}

	public void setMonthCurrencyAmount(int monthCurrencyAmount) {
		this.monthCurrencyAmount = monthCurrencyAmount;
	}

	public short getMonthPayTimes() {
		return monthPayTimes;
	}

	public void setMonthPayTimes(short monthPayTimes) {
		this.monthPayTimes = monthPayTimes;
	}

	public int getFirstPayDate() {
		return firstPayDate;
	}

	public void setFirstPayDate(int firstPayDate) {
		this.firstPayDate = firstPayDate;
	}

	public int getLastPayDate() {
		return lastPayDate;
	}

	public void setLastPayDate(int lastPayDate) {
		this.lastPayDate = lastPayDate;
	}

	public int getTotalCurrencyAmount() {
		return totalCurrencyAmount;
	}

	public void setTotalCurrencyAmount(int totalCurrencyAmount) {
		this.totalCurrencyAmount = totalCurrencyAmount;
	}

	public int getTotalPayTimes() {
		return totalPayTimes;
	}

	public void setTotalPayTimes(int totalPayTimes) {
		this.totalPayTimes = totalPayTimes;
	}

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getGameRegion() {
		return gameRegion;
	}

	public void setGameRegion(String gameRegion) {
		this.gameRegion = gameRegion;
	}

	public int getTrack() {
		return track;
	}

	public void setTrack(int track) {
		this.track = track;
	}

	public int getPayTrack() {
		return payTrack;
	}

	public void setPayTrack(int payTrack) {
		this.payTrack = payTrack;
	}

	public int getLastPayOnlineTime() {
		return lastPayOnlineTime;
	}

	public void setLastPayOnlineTime(int lastPayOnlineTime) {
		this.lastPayOnlineTime = lastPayOnlineTime;
	}

	public java.util.ArrayList<Integer> getOnlineDay() {
		return onlineDay;
	}

	public void setOnlineDay(java.util.ArrayList<Integer> onlineDay) {
		this.onlineDay = onlineDay;
	}

	public java.util.ArrayList<PayInfo> getPayInfoList() {
		return payInfoList;
	}

	public void setPayInfoList(java.util.ArrayList<PayInfo> payInfoList) {
		this.payInfoList = payInfoList;
	}

	public java.util.ArrayList<OnlineDay> getOnlineDayList() {
		return onlineDayList;
	}

	public void setOnlineDayList(java.util.ArrayList<OnlineDay> onlineDayList) {
		this.onlineDayList = onlineDayList;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public byte getGender() {
		return gender;
	}

	public void setGender(byte gender) {
		this.gender = gender;
	}

	public short getAge() {
		return age;
	}

	public void setAge(short age) {
		this.age = age;
	}

	public String getAccountType() {
		return accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getOsVersion() {
		return osVersion;
	}

	public void setOsVersion(String osVersion) {
		this.osVersion = osVersion;
	}

	public String getResolution() {
		return resolution;
	}

	public void setResolution(String resolution) {
		this.resolution = resolution;
	}

	public String getOperators() {
		return operators;
	}

	public void setOperators(String operators) {
		this.operators = operators;
	}

	public int getNetType() {
		return netType;
	}

	public void setNetType(int netType) {
		this.netType = netType;
	}

	public PlayerDayInfo() {
		setActTime(actTime);
		setRegTime(regTime);
		setFirstLoginDate(firstLoginDate);
		setLastLoginDate(lastLoginDate);
		setTotalOnlineDay(totalOnlineDay);
		setTotalLoginTimes(totalLoginTimes);
		setTotalOnlineTime(totalOnlineTime);
		setWeekOnlineDay(weekOnlineDay);
		setWeekLoginTimes(weekLoginTimes);
		setWeekOnlineTime(weekOnlineTime);
		setWeekCurrencyAmount(weekCurrencyAmount);
		setWeekPayTimes(weekPayTimes);
		setMonthOnlineDay(monthOnlineDay);
		setMonthLoginTimes(monthLoginTimes);
		setMonthOnlineTime(monthOnlineTime);
		setMonthCurrencyAmount(monthCurrencyAmount);
		setMonthPayTimes(monthPayTimes);
		setFirstPayDate(firstPayDate);
		setLastPayDate(lastPayDate);
		setTotalCurrencyAmount(totalCurrencyAmount);
		setTotalPayTimes(totalPayTimes);
		setLevel(level);
		setChannel(channel);
		setGameRegion(gameRegion);
		setTrack(track);
		setPayTrack(payTrack);
		setLastPayOnlineTime(lastPayOnlineTime);
		setOnlineDay(onlineDay);
		setPayInfoList(payInfoList);
		setOnlineDayList(onlineDayList);
		setLastLoginTime(lastLoginTime);
		setLastPayAmount(lastPayAmount);
		setLastPayTime(lastPayTime);
	}

	public int hashCode() {
		try {
			throw new Exception("Need define key first!");
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		return 0;
	}

	public java.lang.Object clone() {
		java.lang.Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException ex) {
			assert false; // impossible
		}
		return o;
	}

	public void writeTo(JceOutputStream _os) {
		_os.write(actTime, 0);
		_os.write(regTime, 1);
		_os.write(firstLoginDate, 2);
		_os.write(lastLoginDate, 3);
		_os.write(totalOnlineDay, 4);
		_os.write(totalLoginTimes, 5);
		_os.write(totalOnlineTime, 6);
		_os.write(weekOnlineDay, 7);
		_os.write(weekLoginTimes, 8);
		_os.write(weekOnlineTime, 9);
		_os.write(weekCurrencyAmount, 10);
		_os.write(weekPayTimes, 11);
		_os.write(monthOnlineDay, 12);
		_os.write(monthLoginTimes, 13);
		_os.write(monthOnlineTime, 14);
		_os.write(monthCurrencyAmount, 15);
		_os.write(monthPayTimes, 16);
		_os.write(firstPayDate, 17);
		_os.write(lastPayDate, 18);
		_os.write(totalCurrencyAmount, 19);
		_os.write(totalPayTimes, 20);
		_os.write(level, 21);
		_os.write(channel, 22);
		_os.write(gameRegion, 23);
		_os.write(track, 24);
		_os.write(payTrack, 25);
		_os.write(lastPayOnlineTime, 26);
		if (null != onlineDay) {
			_os.write(onlineDay, 27);
		}
		if (null != payInfoList) {
			_os.write(payInfoList, 28);
		}
		if (null != onlineDayList) {
			_os.write(onlineDayList, 29);
		}
		_os.write(lastLoginTime, 30);
		_os.write(uid, 31);
		_os.write(country, 32);
		_os.write(province, 33);
		_os.write(gender, 34);
		_os.write(age, 35);
		_os.write(accountType, 36);
		_os.write(brand, 37);
		_os.write(osVersion, 38);
		_os.write(resolution, 39);
		_os.write(operators, 40);
		_os.write(netType, 41);
		_os.write(lastPayAmount, 42);
		_os.write(lastPayTime, 43);
	}

	static java.util.ArrayList<Integer> cache_onlineDay;
	static java.util.ArrayList<PayInfo> cache_payInfoList;
	static java.util.ArrayList<OnlineDay> cache_onlineDayList;

	public void readFrom(JceInputStream _is) {
		setActTime((int) _is.read(actTime, 0, true));

		setRegTime((int) _is.read(regTime, 1, true));

		setFirstLoginDate((int) _is.read(firstLoginDate, 2, true));

		setLastLoginDate((int) _is.read(lastLoginDate, 3, true));

		setTotalOnlineDay((int) _is.read(totalOnlineDay, 4, true));

		setTotalLoginTimes((int) _is.read(totalLoginTimes, 5, true));

		setTotalOnlineTime((int) _is.read(totalOnlineTime, 6, true));

		setWeekOnlineDay((byte) _is.read(weekOnlineDay, 7, true));

		setWeekLoginTimes((short) _is.read(weekLoginTimes, 8, true));

		setWeekOnlineTime((int) _is.read(weekOnlineTime, 9, true));

		setWeekCurrencyAmount((int) _is.read(weekCurrencyAmount, 10, true));

		setWeekPayTimes((short) _is.read(weekPayTimes, 11, true));

		setMonthOnlineDay((byte) _is.read(monthOnlineDay, 12, true));

		setMonthLoginTimes((short) _is.read(monthLoginTimes, 13, true));

		setMonthOnlineTime((int) _is.read(monthOnlineTime, 14, true));

		setMonthCurrencyAmount((int) _is.read(monthCurrencyAmount, 15, true));

		setMonthPayTimes((short) _is.read(monthPayTimes, 16, true));

		setFirstPayDate((int) _is.read(firstPayDate, 17, true));

		setLastPayDate((int) _is.read(lastPayDate, 18, true));

		setTotalCurrencyAmount((int) _is.read(totalCurrencyAmount, 19, true));

		setTotalPayTimes((int) _is.read(totalPayTimes, 20, true));

		setLevel((int) _is.read(level, 21, true));

		setChannel(_is.readString(22, true));

		setGameRegion(_is.readString(23, true));

		setTrack((int) _is.read(track, 24, true));

		setPayTrack((int) _is.read(payTrack, 25, true));

		setLastPayOnlineTime((int) _is.read(lastPayOnlineTime, 26, false));

		if (null == cache_onlineDay) {
			cache_onlineDay = new java.util.ArrayList<Integer>();
			Integer __var_1 = 0;
			((java.util.ArrayList<Integer>) cache_onlineDay).add(__var_1);
		}
		setOnlineDay((java.util.ArrayList<Integer>) _is.read(cache_onlineDay,
				27, false));

		if (null == cache_payInfoList) {
			cache_payInfoList = new java.util.ArrayList<PayInfo>();
			PayInfo __var_2 = new PayInfo();
			((java.util.ArrayList<PayInfo>) cache_payInfoList).add(__var_2);
		}
		setPayInfoList((java.util.ArrayList<PayInfo>) _is.read(
				cache_payInfoList, 28, false));

		if (null == cache_onlineDayList) {
			cache_onlineDayList = new java.util.ArrayList<OnlineDay>();
			OnlineDay __var_3 = new OnlineDay();
			((java.util.ArrayList<OnlineDay>) cache_onlineDayList).add(__var_3);
		}
		setOnlineDayList((java.util.ArrayList<OnlineDay>) _is.read(
				cache_onlineDayList, 29, false));
		setLastLoginTime((int) _is.read(lastLoginTime, 30, false));
		setUid((String) _is.read(uid, 31, false));
		setCountry((String) _is.read(country, 32, false));
		setProvince((String) _is.read(province, 33, false));
		setGender((byte) _is.read(gender, 34, false));
		setAge((short) _is.read(age, 35, false));
		setAccountType((String) _is.read(accountType, 36, false));
		setBrand((String) _is.read(brand, 37, false));
		setOsVersion((String) _is.read(osVersion, 38, false));
		setResolution((String) _is.read(resolution, 39, false));
		setOperators((String) _is.read(operators, 40, false));
		setNetType((int) _is.read(netType, 41, false));
		setLastPayAmount((int) _is.read(lastPayAmount, 42, false));
		setLastPayTime((int) _is.read(lastPayTime, 43, false));
	}

	public void display(java.lang.StringBuilder _os, int _level) {
		JceDisplayer _ds = new JceDisplayer(_os, _level);
		_ds.display(actTime, "actTime");
		_ds.display(regTime, "regTime");
		_ds.display(firstLoginDate, "firstLoginDate");
		_ds.display(lastLoginDate, "lastLoginDate");
		_ds.display(totalOnlineDay, "totalOnlineDay");
		_ds.display(totalLoginTimes, "totalLoginTimes");
		_ds.display(totalOnlineTime, "totalOnlineTime");
		_ds.display(weekOnlineDay, "weekOnlineDay");
		_ds.display(weekLoginTimes, "weekLoginTimes");
		_ds.display(weekOnlineTime, "weekOnlineTime");
		_ds.display(weekCurrencyAmount, "weekCurrencyAmount");
		_ds.display(weekPayTimes, "weekPayTimes");
		_ds.display(monthOnlineDay, "monthOnlineDay");
		_ds.display(monthLoginTimes, "monthLoginTimes");
		_ds.display(monthOnlineTime, "monthOnlineTime");
		_ds.display(monthCurrencyAmount, "monthCurrencyAmount");
		_ds.display(monthPayTimes, "monthPayTimes");
		_ds.display(firstPayDate, "firstPayDate");
		_ds.display(lastPayDate, "lastPayDate");
		_ds.display(totalCurrencyAmount, "totalCurrencyAmount");
		_ds.display(totalPayTimes, "totalPayTimes");
		_ds.display(level, "level");
		_ds.display(channel, "channel");
		_ds.display(gameRegion, "gameRegion");
		_ds.display(track, "track");
		_ds.display(payTrack, "payTrack");
		_ds.display(lastPayOnlineTime, "lastPayOnlineTime");
		_ds.display(onlineDay, "onlineDay");
		_ds.display(payInfoList, "payInfoList");
		_ds.display(onlineDayList, "onlineDayList");
	}

	public int getLastLoginTime() {
		return lastLoginTime;
	}

	public void setLastLoginTime(int lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public int getLastPayAmount() {
		return lastPayAmount;
	}

	public void setLastPayAmount(int lastPayAmount) {
		this.lastPayAmount = lastPayAmount;
	}

	public int getLastPayTime() {
		return lastPayTime;
	}

	public void setLastPayTime(int lastPayTime) {
		this.lastPayTime = lastPayTime;
	}
}
