// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `dcsync.jce'
// **********************************************************************

package net.digitcube.hadoop.mapreduce.domain;

import net.digitcube.protocol.JceDisplayer;
import net.digitcube.protocol.JceInputStream;
import net.digitcube.protocol.JceOutputStream;
import net.digitcube.protocol.JceStruct;
import net.digitcube.protocol.JceUtil;

public final class AppDetail extends JceStruct implements java.lang.Cloneable {
	public String className() {
		return "DCSync.AppDetail";
	}

	public String fullClassName() {
		return "com.dataeye.DCSync.AppDetail";
	}

	public String packageName = "";

	public String appName = "";

	public String appVer = "";

	public int installTime = 0;

	public int lastAccessTime = 0;

	public int setUpTimes = 0;

	public int uptime = 0;

	public String ext = "";

	public String getPackageName() {
		return packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	public String getAppName() {
		return appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public String getAppVer() {
		return appVer;
	}

	public void setAppVer(String appVer) {
		this.appVer = appVer;
	}

	public int getInstallTime() {
		return installTime;
	}

	public void setInstallTime(int installTime) {
		this.installTime = installTime;
	}

	public int getLastAccessTime() {
		return lastAccessTime;
	}

	public void setLastAccessTime(int lastAccessTime) {
		this.lastAccessTime = lastAccessTime;
	}

	public int getSetUpTimes() {
		return setUpTimes;
	}

	public void setSetUpTimes(int setUpTimes) {
		this.setUpTimes = setUpTimes;
	}

	public int getUptime() {
		return uptime;
	}

	public void setUptime(int uptime) {
		this.uptime = uptime;
	}

	public String getExt() {
		return ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	public AppDetail() {
		setPackageName(packageName);
		setAppName(appName);
		setAppVer(appVer);
		setInstallTime(installTime);
		setLastAccessTime(lastAccessTime);
		setSetUpTimes(setUpTimes);
		setUptime(uptime);
		setExt(ext);
	}

	public AppDetail(String packageName, String appName, String appVer, int installTime, int lastAccessTime,
			int setUpTimes, int uptime, String ext) {
		setPackageName(packageName);
		setAppName(appName);
		setAppVer(appVer);
		setInstallTime(installTime);
		setLastAccessTime(lastAccessTime);
		setSetUpTimes(setUpTimes);
		setUptime(uptime);
		setExt(ext);
	}

	public boolean equals(Object o) {
		if (o == null) {
			return false;
		}

		AppDetail t = (AppDetail) o;
		return (JceUtil.equals(packageName, t.packageName) && JceUtil.equals(appName, t.appName)
				&& JceUtil.equals(appVer, t.appVer) && JceUtil.equals(installTime, t.installTime)
				&& JceUtil.equals(lastAccessTime, t.lastAccessTime) && JceUtil.equals(setUpTimes, t.setUpTimes)
				&& JceUtil.equals(uptime, t.uptime) && JceUtil.equals(ext, t.ext));
	}

	public int hashCode() {
		try {
			throw new Exception("Need define key first!");
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		return 0;
	}

	public java.lang.Object clone() {
		java.lang.Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException ex) {
			assert false; // impossible
		}
		return o;
	}

	public void writeTo(JceOutputStream _os) {
		_os.write(packageName, 0);
		if (null != appName) {
			_os.write(appName, 1);
		}
		if (null != appVer) {
			_os.write(appVer, 2);
		}
		_os.write(installTime, 3);
		_os.write(lastAccessTime, 4);
		_os.write(setUpTimes, 5);
		_os.write(uptime, 6);
		if (null != ext) {
			_os.write(ext, 7);
		}
	}

	public void readFrom(JceInputStream _is) {
		setPackageName(_is.readString(0, true));

		setAppName(_is.readString(1, false));

		setAppVer(_is.readString(2, false));

		setInstallTime((int) _is.read(installTime, 3, false));

		setLastAccessTime((int) _is.read(lastAccessTime, 4, false));

		setSetUpTimes((int) _is.read(setUpTimes, 5, false));

		setUptime((int) _is.read(uptime, 6, false));

		setExt(_is.readString(7, false));

	}

	public void display(java.lang.StringBuilder _os, int _level) {
		JceDisplayer _ds = new JceDisplayer(_os, _level);
		_ds.display(packageName, "packageName");
		_ds.display(appName, "appName");
		_ds.display(appVer, "appVer");
		_ds.display(installTime, "installTime");
		_ds.display(lastAccessTime, "lastAccessTime");
		_ds.display(setUpTimes, "setUpTimes");
		_ds.display(uptime, "uptime");
		_ds.display(ext, "ext");
	}

}
