// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `item.jce'
// **********************************************************************

package net.digitcube.hadoop.jce.UserExtendInfoLog;

import net.digitcube.protocol.JceDisplayer;
import net.digitcube.protocol.JceInputStream;
import net.digitcube.protocol.JceOutputStream;
import net.digitcube.protocol.JceStruct;
import net.digitcube.protocol.JceUtil;

public final class ExtendInfoDetail extends JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "UserExtendInfoLog.ExtendInfoDetail";
    }

    public String fullClassName()
    {
        return "net.digitcube.hadoop.jce.UserExtendInfoLog.ExtendInfoDetail";
    }

    //玩家在当天购买了一系列道具
    public java.util.ArrayList<ItemDayInfo> itemDayInfoList = null;
    //玩家在当天玩了一系列关卡
    public java.util.ArrayList<LevelDayInfo> levelDayInfoList = null;
    //玩家在当天玩了一系列任务
    public java.util.ArrayList<TaskDayInfo> taskDayInfoList = null;

    public java.util.ArrayList<ItemDayInfo> getItemDayInfoList()
    {
        return itemDayInfoList;
    }

    public void  setItemDayInfoList(java.util.ArrayList<ItemDayInfo> itemDayInfoList)
    {
        this.itemDayInfoList = itemDayInfoList;
    }

    public java.util.ArrayList<LevelDayInfo> getLevelDayInfoList()
    {
        return levelDayInfoList;
    }

    public void  setLevelDayInfoList(java.util.ArrayList<LevelDayInfo> levelDayInfoList)
    {
        this.levelDayInfoList = levelDayInfoList;
    }

    public java.util.ArrayList<TaskDayInfo> getTaskDayInfoList()
    {
        return taskDayInfoList;
    }

    public void  setTaskDayInfoList(java.util.ArrayList<TaskDayInfo> taskDayInfoList)
    {
        this.taskDayInfoList = taskDayInfoList;
    }

    public ExtendInfoDetail()
    {
        setItemDayInfoList(itemDayInfoList);
        setLevelDayInfoList(levelDayInfoList);
        setTaskDayInfoList(taskDayInfoList);
    }

    public ExtendInfoDetail(java.util.ArrayList<ItemDayInfo> itemDayInfoList, java.util.ArrayList<LevelDayInfo> levelDayInfoList, java.util.ArrayList<TaskDayInfo> taskDayInfoList)
    {
        setItemDayInfoList(itemDayInfoList);
        setLevelDayInfoList(levelDayInfoList);
        setTaskDayInfoList(taskDayInfoList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ExtendInfoDetail t = (ExtendInfoDetail) o;
        return (
            JceUtil.equals(itemDayInfoList, t.itemDayInfoList) && 
            JceUtil.equals(levelDayInfoList, t.levelDayInfoList) && 
            JceUtil.equals(taskDayInfoList, t.taskDayInfoList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(JceOutputStream _os)
    {
        if (null != itemDayInfoList)
        {
            _os.write(itemDayInfoList, 0);
        }
        if (null != levelDayInfoList)
        {
            _os.write(levelDayInfoList, 1);
        }
        if (null != taskDayInfoList)
        {
            _os.write(taskDayInfoList, 2);
        }
    }

    static java.util.ArrayList<ItemDayInfo> cache_itemDayInfoList;
    static java.util.ArrayList<LevelDayInfo> cache_levelDayInfoList;
    static java.util.ArrayList<TaskDayInfo> cache_taskDayInfoList;

    public void readFrom(JceInputStream _is)
    {
        if(null == cache_itemDayInfoList)
        {
            cache_itemDayInfoList = new java.util.ArrayList<ItemDayInfo>();
            ItemDayInfo __var_7 = new ItemDayInfo();
            ((java.util.ArrayList<ItemDayInfo>)cache_itemDayInfoList).add(__var_7);
        }
        setItemDayInfoList((java.util.ArrayList<ItemDayInfo>) _is.read(cache_itemDayInfoList, 0, false));

        if(null == cache_levelDayInfoList)
        {
            cache_levelDayInfoList = new java.util.ArrayList<LevelDayInfo>();
            LevelDayInfo __var_8 = new LevelDayInfo();
            ((java.util.ArrayList<LevelDayInfo>)cache_levelDayInfoList).add(__var_8);
        }
        setLevelDayInfoList((java.util.ArrayList<LevelDayInfo>) _is.read(cache_levelDayInfoList, 1, false));

        if(null == cache_taskDayInfoList)
        {
            cache_taskDayInfoList = new java.util.ArrayList<TaskDayInfo>();
            TaskDayInfo __var_9 = new TaskDayInfo();
            ((java.util.ArrayList<TaskDayInfo>)cache_taskDayInfoList).add(__var_9);
        }
        setTaskDayInfoList((java.util.ArrayList<TaskDayInfo>) _is.read(cache_taskDayInfoList, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        JceDisplayer _ds = new JceDisplayer(_os, _level);
        _ds.display(itemDayInfoList, "itemDayInfoList");
        _ds.display(levelDayInfoList, "levelDayInfoList");
        _ds.display(taskDayInfoList, "taskDayInfoList");
    }

}

