// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `item.jce'
// **********************************************************************

package net.digitcube.hadoop.jce.UserExtendInfoLog;

public final class ExtendInfoDetailHolder
{
    public ExtendInfoDetailHolder()
    {
    }
    public ExtendInfoDetailHolder(ExtendInfoDetail value)
    {
        this.value = value;
    }

    public ExtendInfoDetail value;
}
