// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `item.jce'
// **********************************************************************

package net.digitcube.hadoop.jce.UserExtendInfoLog;

import net.digitcube.protocol.JceDisplayer;
import net.digitcube.protocol.JceInputStream;
import net.digitcube.protocol.JceOutputStream;
import net.digitcube.protocol.JceStruct;
import net.digitcube.protocol.JceUtil;

public final class ExtendInfoDetailMap extends JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "UserExtendInfoLog.ExtendInfoDetailMap";
    }

    public String fullClassName()
    {
        return "ExtendInfoDetailMap";
    }

    //Integer --> 数据结算时间
    //ExtendInfoDetail --> 玩家在当天购买道具、玩关卡、任务详情
    public java.util.Map<Integer, ExtendInfoDetail> detailMap = new java.util.HashMap<Integer, ExtendInfoDetail>();

    public java.util.Map<Integer, ExtendInfoDetail> getDetailMap()
    {
        return detailMap;
    }

    public void  setDetailMap(java.util.Map<Integer, ExtendInfoDetail> detailMap)
    {
        this.detailMap = detailMap;
    }

    public ExtendInfoDetailMap()
    {
        setDetailMap(detailMap);
    }

    public ExtendInfoDetailMap(java.util.Map<Integer, ExtendInfoDetail> detailMap)
    {
        setDetailMap(detailMap);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ExtendInfoDetailMap t = (ExtendInfoDetailMap) o;
        return (
            JceUtil.equals(detailMap, t.detailMap) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(JceOutputStream _os)
    {
        if (null != detailMap)
        {
            _os.write(detailMap, 0);
        }
    }

    static java.util.Map<Integer, ExtendInfoDetail> cache_detailMap;

    public void readFrom(JceInputStream _is)
    {
        if(null == cache_detailMap)
        {
            cache_detailMap = new java.util.HashMap<Integer, ExtendInfoDetail>();
            Integer __var_10 = 0;
            ExtendInfoDetail __var_11 = new ExtendInfoDetail();
            cache_detailMap.put(__var_10, __var_11);
        }
        setDetailMap((java.util.Map<Integer, ExtendInfoDetail>) _is.read(cache_detailMap, 0, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        JceDisplayer _ds = new JceDisplayer(_os, _level);
        _ds.display(detailMap, "detailMap");
    }

}

