// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `item.jce'
// **********************************************************************

package net.digitcube.hadoop.jce.UserExtendInfoLog;

public final class ItemCountHolder
{
    public ItemCountHolder()
    {
    }
    public ItemCountHolder(ItemCount value)
    {
        this.value = value;
    }

    public ItemCount value;
}
