// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.25 by WSRD Tencent.
// Generated from `item.jce'
// **********************************************************************

package net.digitcube.hadoop.jce.UserExtendInfoLog;

public final class TaskDayInfoHolder
{
    public TaskDayInfoHolder()
    {
    }
    public TaskDayInfoHolder(TaskDayInfo value)
    {
        this.value = value;
    }

    public TaskDayInfo value;
}
